### ISSUE TITLE
change dockerfile alpine versions

### ISSUE THREAD

**Issue by aairom** [thomassuedbroecker/extension-apis#1]
change in the dockerfile alpine versions to 20 or 20+
and remove apk lines

**Comment by thomassuedbroecker** [comment]
Thanks for the feedback.

**Comment by thomassuedbroecker** [comment]
Fix in: https://github.com/thomassuedbroecker/extension-apis/commit/28a39b0c464175b0ec0601c4fa1b382191855f49
